# Service definition for Grafana
apiVersion: v1
kind: Service
metadata:
  name: grafana-service # Unique name for the Grafana service
spec:
  selector:
    app: monitoring-solution # Selector matching the labels of the pods to target
  ports:
  - protocol: TCP # Network protocol used by the service
    port: 80 # Port the service listens on
    targetPort: 3000 # Target port on the pod (Grafana listens on 3000)
  type: LoadBalancer # Expose the service outside the cluster using a cloud provider's load balancer

---

# Service definition for Prometheus
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service # Unique name for the Prometheus service
spec:
  selector:
    app: monitoring-solution # Selector matching the labels of the pods to target
  ports:
  - protocol: TCP # Network protocol used by the service
    port: 9090 # Port the service listens on, matching Prometheus' default port
    targetPort: 9090 # Target port on the pod (Prometheus listens on 9090)
  type: LoadBalancer # Expose the service outside the cluster using a cloud provider's load balancer
