monitoring-solution-deployment.yaml# This section is the header of the Kubernetes manifest file, defining the kind of Kubernetes object (Deployment) and its API version.
apiVersion: apps/v1
kind: Deployment

# The metadata section provides details about the deployment object, such as its name.
metadata:
  name: monitoring-solution-deployment # The name of the deployment.

# The spec (specification) section defines the desired state of the deployment.
spec:
  replicas: 1 # Specifies the number of pod replicas. Here, it's set to 1, meaning only one pod will be created for this deployment.

  # The selector field defines how the deployment finds which pods to manage. In this case, it matches labels.
  selector:
    matchLabels:
      app: monitoring-solution # The deployment manages pods with the label 'app' set to 'monitoring-solution'.

  # The template field contains the template for the pods the deployment manages.
  template:
    metadata:
      labels:
        app: monitoring-solution # Labels applied to pods created from this template, matching the selector above.

    # The spec within the template defines the configuration of the pods.
    spec:
      containers:
      - name: grafana-container # Name of the container within the pod.
        image: grafana/grafana:latest # The Docker image for the container, here it's the latest Grafana image.
        ports:
        - containerPort: 3000 # The container port that Grafana listens on. This should be accessible within the cluster.
